version: '3.7'

services:
  database:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: asdfasdf
      MYSQL_DATABASE: asdfads
      MYSQL_USER: asfads
      MYSQL_PASSWORD: asfdsd
    ports:
      - 3306:3306
    restart: always
    volumes:
     - ./mariadb:/var/lib/mysql
